# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de212c7ccbfa405ecdf707a52ff6c9b58d8523c71764c7f06d02b7bf3e41723bf15e2e09f7df46e21e0e34327999a4288c521f5ae0b4b8b5d95239a1b54bd92f

test:
  secret_key_base: c315a209ee695e7b3a9ed27bced669caec9b44ea56379e90c2e5ef91c3d77d1f3b4425a36dcf86af86611db0a6d710349aed7b5a32e2cd1743b33856fa0fd4f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
